example
exampleConcept
	^ '     <ContentElement xsi:type="uma:Concept" name="story_points" briefDescription="A story point is a relative estimate of the &quot;size&quot; of the work compared to other work on the project." id="_28Gp8F6AEd22Gu98eFOlrQ" orderingGuide="" presentationName="Story Points" suppressed="false" isAbstract="false" variabilityType="na">
        <Presentation name="new_concept,_28Gp8F6AEd22Gu98eFOlrQ" briefDescription="" id="-ILQMonu5qLiOKjvMlGtDPg" orderingGuide="" presentationName="My presentation" suppressed="false" authors="" changeDate="2008-07-31T08:47:49" changeDescription="" version="" externalId="">
          <MainDescription><![CDATA[<p>
    Story points are probably the most commonly used estimating unit among agile teams today.&nbsp; The name&nbsp;is
    derived from agile teams commonly expressing requirements as “user stories”.&nbsp;&nbsp;A story point is a relative
    estimate of the "size" of the work compared to other work on the project.&nbsp;So,&nbsp;a 10-point user story is
    expected to take twice as long as a 5-point user story.
</p>
<p>
    Estimates are not quantified but implicitly&nbsp;include&nbsp;the&nbsp;team''s collective&nbsp;understanding of the
    complexity, risk and time for&nbsp;the work being estimated.&nbsp; A story point is unique to the team and cannot be
    compared with a story point on another team.&nbsp;&nbsp;It can be counter productive to map&nbsp;story points to
    their&nbsp;absolute time equivalent and the accepted technique&nbsp;for predicting time to completion is the team''s
    velocity.
</p>]]></MainDescription>
          <KeyConsiderations></KeyConsiderations>
        </Presentation>
      </ContentElement>'